{% set name = "ml_dtypes" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ml_dtypes-{{ version }}.tar.gz
  sha256: c4a7f2ea1d17f8a0caee4c99ccfb8814713ba620dea1cc8ab4f478df250dba25

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cross-python_{{ target_platform }}   # [build_platform != target_platform]
    - python                               # [build_platform != target_platform]
    - numpy                                # [build_platform != target_platform]
    - pybind11 >=2.10.0,<2.11.dev0         # [build_platform != target_platform]
  host:
    - python
    - numpy
    - pybind11 >=2.10.0,<2.11.dev0
    - setuptools >=67.6.0,<67.7.dev0
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - ml_dtypes
  commands:
    - pip check
    - pytest -n auto
  source_files:
    - ml_dtypes/tests
  requires:
    - pip
    - pytest
    - pytest-xdist
    - pylint >=2.6.0
    - pyink
    - absl-py

about:
  home: https://pypi.org/project/ml-dtypes/
  summary: A stand-alone implementation of several NumPy dtype extensions used in machine learning
  dev_url: https://github.com/jax-ml/ml_dtypes
  doc_url: https://github.com/jax-ml/ml_dtypes
  license: MPL-2.0 AND Apache-2.0
  license_file:
    - LICENSE.eigen
    - LICENSE

extra:
  recipe-maintainers:
    - ngam
