{% set name = "ml_dtypes" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ml_dtypes-{{ version }}.tar.gz
  sha256: 60778f99194b4c4f36ba42da200b35ef851ce4d4af698aaf70f5b91fe70fc611

build:
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cross-python_{{ target_platform }}   # [build_platform != target_platform]
    - python                               # [build_platform != target_platform]
    - numpy                                # [build_platform != target_platform]
    - pybind11 >=2.11.1,<2.12.dev0         # [build_platform != target_platform]
  host:
    - python
    - numpy
    - pybind11 >=2.11.1,<2.12.dev0
    - setuptools >=68.1.0,<68.2.dev0
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - ml_dtypes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ml-dtypes/
  summary: A stand-alone implementation of several NumPy dtype extensions used in machine learning
  dev_url: https://github.com/jax-ml/ml_dtypes
  doc_url: https://github.com/jax-ml/ml_dtypes
  license: MPL-2.0 AND Apache-2.0
  license_file:
    - LICENSE.eigen
    - LICENSE

extra:
  recipe-maintainers:
    - ngam
    - xhochy
