{% set name = "ml_dtypes" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ml_dtypes-{{ version }}.tar.gz
  sha256: 8ab06a50fb9bf9666dd0fe5dfb4676fa2b0ac0f31ecff72a6c3af8e22c063453

build:
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}   # [build_platform != target_platform]
    - python                               # [build_platform != target_platform]
    - numpy                                # [build_platform != target_platform]
  host:
    - python
    - numpy
    - setuptools
    - pip
    - wheel
  run:
    - python

test:
  imports:
    - ml_dtypes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ml-dtypes/
  summary: A stand-alone implementation of several NumPy dtype extensions used in machine learning
  dev_url: https://github.com/jax-ml/ml_dtypes
  doc_url: https://github.com/jax-ml/ml_dtypes
  license: MPL-2.0 AND Apache-2.0
  license_file:
    - LICENSE.eigen
    - LICENSE

extra:
  recipe-maintainers:
    - ngam
    - xhochy
